localhost:
    server:
        host:                               'http://localhost:4000'
    transaction_engine:
        host:                               'localhost'
        port:                               '4000'
        ssl:                                false
        open_timeout:                       5
        read_timeout:                       5
        secret:                             c6af25e263004d959a35f7776b0679ee